require: rubocop-performance
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'spec/**/**/*'
Performance/RegexpMatch:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
LineLength:
  Max: 100
Lint/RescueException:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
